source 'https://rubygems.org'

gem 'activerecord', '~> 4.2.1'
gem 'bundler'
gem 'rake'
gem 'sinatra', '~> 1.4.6'
gem 'sinatra-assetpack', '~> 0.3.3'
gem 'slim', '~> 3.0.6'
gem 'sqlite3', '~> 1.3.10'
gem 'sys-filesystem', '~> 1.1.3'
