version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          - RACK_ENV=test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: myapp
          POSTGRES_DB: dritorjan_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      # - run:
      #     name: Install System Dependencies
      #     command: apt-get update -qq && apt-get install -y postgresql
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Configure database settings
          command: mv config/database.circleci.yml config/database.yml
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5433 -timeout 1m
      - run:
          name: Setup database
          command: bundle exec rake database:create database:create_tables
      - run:
          name: Run tests
          command: bundle exec rake test
      - run:
          name: Check code style
          command: bundle exec rubocop
