version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          - RACK_ENV=test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: dritorjan
          POSTGRES_DB: dritorjan_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Configure database settings
          command: mv config/database.circleci.yml config/database.yml
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup database
          command: bundle exec rake database:create_tables
      - run:
          name: Run tests
          command: bundle exec rake test
      - run:
          name: Check code style
          command: bundle exec rubocop
