version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - type: cache-restore
        key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle install
      - type: cache-save
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: Configure database settings
          command: mv config/database.example.yml config/database.yml
      - run:
          name: Setup database
          command: bundle exec rake database:create database:create_tables
      - run:
          name: Run tests
          command: bundle exec rake test
      - run:
          name: Check code style
          command: bundle exec rubocop
