version: 2
jobs:
  build:
    # working_directory: ./
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mv config/database.example.yml config/database.yml
      - run:
          name: Setup database
          command: bundle exec rake database:create database:create_tables

# machine:
#   ruby:
#     version: 2.4.1
# database:
#   override:
#     - mv config/database.example.yml config/database.yml
#     - bundle exec rake database:create
#     - bundle exec rake database:create_tables
# test:
#   post:
#     - bundle exec rubocop
