file_manager:
  directories:
    - ./tmp
    - /home/user/downloads
  old_entries_threshold_in_minutes: 60
oioioi:
  directory: ./oioioi
steve_snapshotter:
  directory: ./steve-snapshots
  url: http://uri-to-steve/?action=snapshot
