file_manager:
  directories:
    - ./tmp
    - /home/user/downloads
  old_entries_threshold_in_minutes: 90
oioioi:
  directory: ./oioioi
sidekiq:
  username: ''
  password: ''
steve_snapshotter:
  directory: ./steve-snapshots
  url: http://uri-to-steve/?action=snapshot
