file_manager:
  directories:
    - ./tmp
    - /home/user/downloads
oioioi:
  directory: ./oioioi
sidekiq:
  username: ''
  password: ''
steve_snapshotter:
  directory: ./steve-snapshots
  url: http://uri-to-steve/?action=snapshot
