file_manager:
  directories:
    - ./tmp
    - /home/user/downloads
  min_free_space: 10737418240 # 10 Go in octets
  old_entries_threshold_in_minutes: 60
  root_directory: /
host: localhost
oioioi:
  directory: ./oioioi
steve_snapshotter:
  directory: ./steve-snapshots
  url: http://uri-to-steve/?action=snapshot
