:schedule:
  files_remover:
    class: Dritorjan::Jobs::FilesRemover
    description: Delete files to free disk space
    every: ['1h', first_in: '0s']
  empty_directories_remover:
    class: Dritorjan::Jobs::EmptyDirectoriesRemover
    description: Remove empty directories
    every: ['1h', first_in: '0s']
  entries_cleaner:
    class: Dritorjan::Jobs::EntriesCleaner
    description: Remove old entries
    every: ['1h', first_in: '15m']
  oioioi_downloader:
    class: Dritorjan::Jobs::OioioiDownloader
    description: Download mp3s from oioioi.ru
    every: ['1d', first_in: '0s']
  scan_runner:
    class: Dritorjan::Jobs::ScanRunner
    description: Scan folders and register files
    every: ['1h', first_in: '0s']
  steve_snapshotter:
    class: Dritorjan::Jobs::SteveSnapshotter
    description: Take a snapshot of Steve and save the file
    every: ['1m', first_in: '0s']
