file_manager:
  directories:
    - ./tmp
  old_entries_threshold_in_minutes: 90
oioioi:
  directory: ./tmp/oioioi
steve_snapshotter:
  directory: ./tmp/steve-snapshots
  url: http://uri-to-steve/?action=snapshot
