file_manager:
  directories:
    - ./tmp
  min_free_space: 10_737_418_240 # 10 Go in octets
  old_entries_threshold_in_minutes: 60
oioioi:
  directory: ./tmp/oioioi
steve_snapshotter:
  directory: ./tmp/steve-snapshots
  url: http://uri-to-steve/?action=snapshot
